name: Check Raspberry Pi Connection

on: push

jobs:
    make-dir:
        runs-on: ubuntu-latest
        steps:
            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

            - name: Create Directory
              run: |
                  ssh -o ProxyCommand="openssl s_client -connect %h:443 -servername %h -quiet" $SSH_USER << 'EOF'
                    cd ~/apps || exit 1
                    mkdir remotedir
                    cd remotedir
                    touch README.md
                  EOF
