name: 08 - Using Variables

on:
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: 'I am a workflow env var'
    OVERRIDDEN: 'Overridden var'

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am a job env var'
            OVERRIDDEN: 'Overridden by job'
        steps:
            - name: Print Env Variables
              env:
                  STEP_VAR: 'I am a step env var'
                  STEP_VAR_2: 'Another step var'
              run: |
                  echo "Step env var: ${{env.STEP_VAR}}"
                  echo "Step env var 2: $STEP_VAR_2"
                  echo "Job env var: ${{env.JOB_VAR}}"
                  echo "Workflow env var: $WORKFLOW_VAR"
                  echo "Overridden env var: ${{env.OVERRIDDEN}}"
    echo-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Print Variables
              run: |
                  echo "Repo var: ${{vars.REPO_VAR}}"
                  echo "Overwritten var: ${{vars.OVERWRITTEN_VAR}}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Print Prod Variables
              run: |
                  echo "Repo var: ${{vars.REPO_VAR}}"
                  echo "environment var: ${{vars.TARGET_VAR}}"
                  echo "Overwritten var: ${{vars.OVERWRITTEN_VAR}}"
