name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 22.x
                default: 22.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{inputs.node-version}}
            - name: Install Dependencies
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Building
              run: npm run build
            - name: Deploying
              run: echo "Deploying to nonprod"

        # 1. Checkout the code
        # 2. Install dependencies
        # 3. Linting, unit testing, Building
        # 4. Deploy to a nonprod environment
