name: 14 - Working with artifacts

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
            - name: Download Cached Dependencies
              uses: actions/cache@v4
              id: cache
              with:
                  path: 04-using-actions/react-app
                  key: deps-node-modules-${{hashFiles('04-using-actions/react-app/package-lock.json')}}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Build code
              run: npm run build
            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                  name: app
                  path: 04-using-actions/react-app/dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: app
                  path: dist
            - name: Show folder structure
              run: ls -R
