name: 16 - Working With Environments
run-name: 16 - Working With Environments | ${{inputs.target-env}}

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default-value'}}
        steps:
            - name: Echo vars
              run: |
                  echo "Env vars: ${{vars.TARGET_VAR}}"
                  echo "Env value: ${{env.my-env-value}}"
