name: 17 - Custom Actions - Composite
run-name: 17 - Custom Actions - Composite | ${{inputs.target-env}}

on:
    workflow_dispatch:
        inputs:
            target-env:
                description: Which env to target for dependencies installation
                type: choice
                options:
                    - dev
                    - prod

env:
    working-directory: 04-using-actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                  node-version: 22.x
                  working-dir: ${{env.working-directory}}
                  target-env: ${{inputs.target-env}}
            - name: Linting
              run: npm run lint
            - name: Building
              run: npm run build
