name: 18 - JS Custom Actions
run-name: 18 - JS Custom Actions

on:
    workflow_dispatch:

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
